service: queing-testing

provider:
  name: aws
  memory: 256
  runtime: nodejs8.10
  region: us-east-1

  iamRoleStatements:
    # Allow the lambdas to invoke other lambdas, and to interact with DynamoDB
    - Effect: "Allow"
      Action:
        - sqs:ChangeMessageVisibility
        - lambda:InvokeAsync
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - sqs:ReceiveMessage
        - kinesis:DescribeStream
        - kinesis:DescribeStreamSummary
        - kinesis:GetRecords
        - kinesis:GetShardIterator
        - kinesis:ListShards
        - kinesis:ListStreams
        - kinesis:SubscribeToShard
      Resource:
        - "*"

functions:
  sqs-test:
    handler: src/lambdas/sqs-handler.handler
  kinesis-test:
    handler: src/lambdas/kinesis-handler.handler
